# base interface
CIRCUIT_UI_HEIGHT = 200
MODULE_UI_HEIGHT = 200

MODULES_PER_LINE = 5

SCREEN_WIDTH = 800
SCREEN_HEIGHT = CIRCUIT_UI_HEIGHT + MODULE_UI_HEIGHT

LINEWIDTH = 2
LINESPACE = 40

MODULE_SIZE = 30